/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DomiciliationService } from "../domiciliation.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DomiciliationCreateInput } from "./DomiciliationCreateInput";
import { Domiciliation } from "./Domiciliation";
import { DomiciliationFindManyArgs } from "./DomiciliationFindManyArgs";
import { DomiciliationWhereUniqueInput } from "./DomiciliationWhereUniqueInput";
import { DomiciliationUpdateInput } from "./DomiciliationUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DomiciliationControllerBase {
  constructor(
    protected readonly service: DomiciliationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Domiciliation })
  @nestAccessControl.UseRoles({
    resource: "Domiciliation",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: DomiciliationCreateInput,
  })
  async createDomiciliation(
    @common.Body() data: DomiciliationCreateInput
  ): Promise<Domiciliation> {
    return await this.service.createDomiciliation({
      data: {
        ...data,

        address: {
          connect: data.address,
        },

        employees: {
          connect: data.employees,
        },
      },
      select: {
        address: {
          select: {
            id: true,
          },
        },

        createdAt: true,

        employees: {
          select: {
            id: true,
          },
        },

        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Domiciliation] })
  @ApiNestedQuery(DomiciliationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Domiciliation",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async domiciliations(
    @common.Req() request: Request
  ): Promise<Domiciliation[]> {
    const args = plainToClass(DomiciliationFindManyArgs, request.query);
    return this.service.domiciliations({
      ...args,
      select: {
        address: {
          select: {
            id: true,
          },
        },

        createdAt: true,

        employees: {
          select: {
            id: true,
          },
        },

        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Domiciliation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Domiciliation",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async domiciliation(
    @common.Param() params: DomiciliationWhereUniqueInput
  ): Promise<Domiciliation | null> {
    const result = await this.service.domiciliation({
      where: params,
      select: {
        address: {
          select: {
            id: true,
          },
        },

        createdAt: true,

        employees: {
          select: {
            id: true,
          },
        },

        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Domiciliation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Domiciliation",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: DomiciliationUpdateInput,
  })
  async updateDomiciliation(
    @common.Param() params: DomiciliationWhereUniqueInput,
    @common.Body() data: DomiciliationUpdateInput
  ): Promise<Domiciliation | null> {
    try {
      return await this.service.updateDomiciliation({
        where: params,
        data: {
          ...data,

          address: {
            connect: data.address,
          },

          employees: {
            connect: data.employees,
          },
        },
        select: {
          address: {
            select: {
              id: true,
            },
          },

          createdAt: true,

          employees: {
            select: {
              id: true,
            },
          },

          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Domiciliation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Domiciliation",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDomiciliation(
    @common.Param() params: DomiciliationWhereUniqueInput
  ): Promise<Domiciliation | null> {
    try {
      return await this.service.deleteDomiciliation({
        where: params,
        select: {
          address: {
            select: {
              id: true,
            },
          },

          createdAt: true,

          employees: {
            select: {
              id: true,
            },
          },

          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
