/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Structure } from "./Structure";
import { StructureCountArgs } from "./StructureCountArgs";
import { StructureFindManyArgs } from "./StructureFindManyArgs";
import { StructureFindUniqueArgs } from "./StructureFindUniqueArgs";
import { CreateStructureArgs } from "./CreateStructureArgs";
import { UpdateStructureArgs } from "./UpdateStructureArgs";
import { DeleteStructureArgs } from "./DeleteStructureArgs";
import { EmployeeFindManyArgs } from "../../employee/base/EmployeeFindManyArgs";
import { Employee } from "../../employee/base/Employee";
import { StructureService } from "../structure.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Structure)
export class StructureResolverBase {
  constructor(
    protected readonly service: StructureService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Structure",
    action: "read",
    possession: "any",
  })
  async _structuresMeta(
    @graphql.Args() args: StructureCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Structure])
  @nestAccessControl.UseRoles({
    resource: "Structure",
    action: "read",
    possession: "any",
  })
  async structures(
    @graphql.Args() args: StructureFindManyArgs
  ): Promise<Structure[]> {
    return this.service.structures(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Structure, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Structure",
    action: "read",
    possession: "own",
  })
  async structure(
    @graphql.Args() args: StructureFindUniqueArgs
  ): Promise<Structure | null> {
    const result = await this.service.structure(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Structure)
  @nestAccessControl.UseRoles({
    resource: "Structure",
    action: "create",
    possession: "any",
  })
  async createStructure(
    @graphql.Args() args: CreateStructureArgs
  ): Promise<Structure> {
    return await this.service.createStructure({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Structure)
  @nestAccessControl.UseRoles({
    resource: "Structure",
    action: "update",
    possession: "any",
  })
  async updateStructure(
    @graphql.Args() args: UpdateStructureArgs
  ): Promise<Structure | null> {
    try {
      return await this.service.updateStructure({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Structure)
  @nestAccessControl.UseRoles({
    resource: "Structure",
    action: "delete",
    possession: "any",
  })
  async deleteStructure(
    @graphql.Args() args: DeleteStructureArgs
  ): Promise<Structure | null> {
    try {
      return await this.service.deleteStructure(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Employee], { name: "employees" })
  @nestAccessControl.UseRoles({
    resource: "Employee",
    action: "read",
    possession: "any",
  })
  async findEmployees(
    @graphql.Parent() parent: Structure,
    @graphql.Args() args: EmployeeFindManyArgs
  ): Promise<Employee[]> {
    const results = await this.service.findEmployees(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
