/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { OrientationService } from "../orientation.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { OrientationCreateInput } from "./OrientationCreateInput";
import { Orientation } from "./Orientation";
import { OrientationFindManyArgs } from "./OrientationFindManyArgs";
import { OrientationWhereUniqueInput } from "./OrientationWhereUniqueInput";
import { OrientationUpdateInput } from "./OrientationUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class OrientationControllerBase {
  constructor(
    protected readonly service: OrientationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Orientation })
  @nestAccessControl.UseRoles({
    resource: "Orientation",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: OrientationCreateInput,
  })
  async createOrientation(
    @common.Body() data: OrientationCreateInput
  ): Promise<Orientation> {
    return await this.service.createOrientation({
      data: data,
      select: {
        activity: true,
        createdAt: true,
        geographicDomain: true,
        id: true,
        structureCode: true,
        structureLabel: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Orientation] })
  @ApiNestedQuery(OrientationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Orientation",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async orientations(@common.Req() request: Request): Promise<Orientation[]> {
    const args = plainToClass(OrientationFindManyArgs, request.query);
    return this.service.orientations({
      ...args,
      select: {
        activity: true,
        createdAt: true,
        geographicDomain: true,
        id: true,
        structureCode: true,
        structureLabel: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Orientation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Orientation",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async orientation(
    @common.Param() params: OrientationWhereUniqueInput
  ): Promise<Orientation | null> {
    const result = await this.service.orientation({
      where: params,
      select: {
        activity: true,
        createdAt: true,
        geographicDomain: true,
        id: true,
        structureCode: true,
        structureLabel: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Orientation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Orientation",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: OrientationUpdateInput,
  })
  async updateOrientation(
    @common.Param() params: OrientationWhereUniqueInput,
    @common.Body() data: OrientationUpdateInput
  ): Promise<Orientation | null> {
    try {
      return await this.service.updateOrientation({
        where: params,
        data: data,
        select: {
          activity: true,
          createdAt: true,
          geographicDomain: true,
          id: true,
          structureCode: true,
          structureLabel: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Orientation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Orientation",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteOrientation(
    @common.Param() params: OrientationWhereUniqueInput
  ): Promise<Orientation | null> {
    try {
      return await this.service.deleteOrientation({
        where: params,
        select: {
          activity: true,
          createdAt: true,
          geographicDomain: true,
          id: true,
          structureCode: true,
          structureLabel: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
